feat: various fixes enhancements
pubky/pubky-beta pull request #172
Opened 2024-04-18 21:24 UTC by MiguelMedeiros

- [x] infinite scrolling for profile page
- [x] feat: make all skeletons loadspinners
- [x] fix post caching as a usestate in client.context
- [x] infinite scrolling for search page
- [x] sticky sidebar for search page
- [x] grid and layout views fix height and limit content
- [x] add loader to contacts/following/followers/hottags/post
- [x] add cache to posts content
- [x] add new created post to the list of posts
- [x] add top bar preloader
- [x] add cache for tags content

2024-04-22 18:46 UTC, flaviomoceri requested changes
The two commits that I made:

- I used `text-opacity-20` instead of `text-gray-600` to respect the pattern we use. We never use gray.
- I set `items-start justify-start` in UserPic because then this effect appears if a user have just 1 follower/following

![Screenshot 2024-04-22 203254](https://github.com/synonymdev/pubky-app/assets/63161412/66216ab7-9cda-48f8-8a2a-2c5d070ae77e)


Please take a look at:
- /search page
![Screenshot 2024-04-22 203450](https://github.com/synonymdev/pubky-app/assets/63161412/f46ad697-d7c6-46c6-ab11-eb71784d1ba9)

- in `/home` if I reload the page `No post yet` appears, after 1sec `Loading post` and finally the posts

- In Contacts.List and Contacts.Ranking we need `{index !== contactsLength - 1 && <Content.Divider />}`, because if there is only one item the divider must not appear

- Why did you put this minimum height in Component.Post, I don't think it's in the figma and I don't like it very much
![Screenshot 2024-04-22 205301](https://github.com/synonymdev/pubky-app/assets/63161412/64a923a9-515d-451d-9c2a-0ce7508553c0)


- Why did you comment out the metadata?

![Screenshot 2024-04-22 204431](https://github.com/synonymdev/pubky-app/assets/63161412/540d5541-867c-42c9-8a97-9460560939bd)

2024-04-22 21:32 UTC, MiguelMedeiros commented
@flaviomoceri fixed all issues metioned in your last comment.

2024-04-23 06:13 UTC, flaviomoceri commented
With your changes it seems you also fixed a bug: 🎉
https://github.com/synonymdev/pubky-app/issues/177

2024-04-23 06:13 UTC, flaviomoceri approved these changes

2024-04-23 06:14 UTC, merged